service:
  defaultMinMs: 20
  defaultMaxMs: 50

logging:
  level:
    root: WARN
    # Get info regarding connection to the cofig server and retries if required
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG
    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.UndertowEmbeddedServletContainer: INFO
    se.callista: INFO
  
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 3
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:ML-${spring.application.name}:${spring.application.instance_id:${random.value}}}
#  client:
#    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
#    registryFetchIntervalSeconds: 5
#    instanceInfoReplicationIntervalSeconds: 5
#    initialInstanceInfoReplicationIntervalSeconds: 5
  
  
  
