service:
  defaultMinMs: 200
  defaultMaxMs: 500
  
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 3
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:ML-${spring.application.name}:${spring.application.instance_id:${random.value}}}
#  client:
#    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
#    registryFetchIntervalSeconds: 5
#    instanceInfoReplicationIntervalSeconds: 5
#    initialInstanceInfoReplicationIntervalSeconds: 5
  
  
  
